version: "3.8"

services:
  api-qr:
    build:
      context: ./api-qr
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork
    depends_on:
      - api-stats

  api-stats:
    build:
      context: ./api-stats
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
